# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db16626b1bdbae37895872448c459b9ad362a7abfed8e2093f8ec0991295935256019939506cd1bd04f863fef4dfdd5fad5d6e10b5d591737eea9e8bb8e89289

test:
  secret_key_base: 5d0a2f958ff115e41a7f46123c1d3082da2f7406f78f3f184a5cb401330f238b35363feae42639e0280ab3f93808cd09d408ab3327fbf06ccfc7dffd4f3ab7e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
